accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name="logout"),
]

groups/urls.py
from django.urls import path
from . import views
app_name = 'groups'

urlpatterns = [
    path('',views.GroupList.as_view(),name='list'),
    path('create/',views.GroupCreate.as_view(),name="create"),
    path('posts/in/<slug>',views.GroupDetail.as_view(),name="detail"),
    path('join/<slug>',views.GroupJoin.as_view(),name='join'),
    path('leave/<slug>',views.GroupLeave.as_view(),name='leave'),
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'


urlpatterns = [
    path('', views.PostList.as_view(), name='list'),
    path('create/', views.PostCreate.as_view(), name='create'),
    path('by/<username>/<pk>', views.PostDetail.as_view(), name='detail'),
    path('by/<username>/', views.UserPosts.as_view(), name='userposts'),
    path('delete/<pk>/', views.PostDelete.as_view(), name='delete'),
    path('update/<pk>/',views.PostUpdate.as_view(), name='update'),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('bye/',views.ByePage.as_view(),name='bye'),
    path('groups/',include('groups.urls')),
    path('posts/', include('posts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return "@{}".format(self.username)

groups/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField()
    members = models.ManyToManyField(User,through='GroupMember')
    
    def __str__(self):
        return self.name
        
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)
        
    def get_absolute_url(self):
        return reverse('groups:detail',kwargs={'slug':self.slug}) 
    
    class Meta:
        ordering=['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
        
    class Meta:
        unique_together = ('group','user')

posts/models.py
from django.db import models
from groups.models import Group
from django.contrib.auth import get_user_model
User = get_user_model()

from django.urls import reverse


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={
                                        'username': self.user.username,
                                        'pk': self.pk
                                    })
                                    
    class Meta:
        ordering = ['-created_at']

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserCreateForm(UserCreationForm):
    
    class Meta:
        # fields = '__all__'
        fields = ('username','email','password1','password2')
        model = get_user_model()
    

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from . import forms
from django.urls import reverse_lazy
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('accounts:login')

groups/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (ListView,CreateView,
                                DetailView,RedirectView)
from .models import Group, GroupMember
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.contrib import messages
from django.db import IntegrityError

# Create your views here.
class GroupList(ListView):
    model = Group

class GroupCreate(LoginRequiredMixin, CreateView):
    model = Group
    fields = ('name','description')
    
class GroupDetail(DetailView):
    model = Group

class GroupJoin(LoginRequiredMixin,RedirectView):
    
    # 코드 실행 후 리다이렉트 할 주소 설정
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:detail',kwargs={'slug':self.kwargs.get('slug')})
    # 코드실행
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        
        # 이거 실행해
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        # 애러났어?
        except IntegrityError:
            messages.warning(self.request,'already a member')
        # 애러 안남
        else:
            messages.success(self.request,'add a new member')
            
        return super().get(request,*args,**kwargs)
        
class GroupLeave(LoginRequiredMixin,RedirectView):
    # 코드 실행 후 리다이렉트 할 주소 설정
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:detail',kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self,request,*args,**kwargs):
        try:
            membership = GroupMember.objects.filter(
                            user = self.request.user,
                            group__slug = self.kwargs.get('slug')
                            ).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'sorry')
        else:
            membership.delete()
            messages.success(self.request, 'delete!!')        
        
        return super().get(request,*args,**kwargs)

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth import get_user_model
User = get_user_model()

from django.urls import reverse_lazy


# Create your views here.
class PostList(ListView):
    model = Post
    
# 로그인 한 사람만이 볼수 있게
class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'message', 'group')
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class PostDetail(DetailView):
    model = Post
    
class UserPosts(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'
    
    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('post_set').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.post_set.all()
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context
        
class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:list')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user)
        
    
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('title', 'message')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user)
    

social/views.py
from django.views.generic import TemplateView

# CBV 기초
class HomePage(TemplateView):
    template_name = 'index.html'
    
class ByePage(TemplateView):
    template_name = 'bye.html'

accounts/templates/accounts/login.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{%block content%}
    <h1>여기는 로그인</h1>
    <div class="container">
        <form action="" method='post'>
            {%csrf_token%}
            {% bootstrap_form form %}
            <input type="submit">
        </form>
    </div>
{%endblock%}

accounts/templates/accounts/signup.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{%block content%}
    <div class="container">
        <form action="" method='post'>
            {%csrf_token%}
            {% bootstrap_form form %}
            <input type="submit">
        </form>
    </div>
{%endblock%}

groups/templates/groups/group_base.html
{%extends 'base.html'%}

{%block content%}
    <!--<h1>여기는 group_base.html입니다.</h1>-->
    <div class="container">
        <div class="row">
            {%block pregroup%} {%endblock%}
            {%block group_content%} {%endblock%}
            {%block postgroup%} {%endblock%}
        </div>
    </div>
{%endblock%}

groups/templates/groups/group_detail.html
{%extends 'groups/group_base.html'%}

{%block pregroup%}
    <h1>{{group.name}}</h1>
    <h2>member count : {{group.members.count}}</h2>
    <p>{{group.description}}</p>
    
    {% if user in group.members.all %}
    <!--유저가 이 그룹에 속해있을때-->
        <a href="{%url 'groups:leave' slug=group.slug%}" class="btn btn-warning">
            <i class="fas fa-trash-alt"></i>leave
        </a>
    {% else %}
    <!--유저가 이 그룹에 속해 있지 않을때-->
        <a href="{%url 'groups:join' slug=group.slug%}" class='btn btn-warning'>
            <i class="fas fa-check-circle"></i>Join
        </a>
    {% endif %}
{%endblock%}

groups/templates/groups/group_form.html
{%extends 'groups/group_base.html'%}
{% load bootstrap4 %}
{%block group_content%}
    
    <form method='post'>
        {%csrf_token%}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
    
{%endblock%}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
<!--유저정보 출력-->
    <div class="col-md-4">
        {% if user.is_authenticated %}
            <h2>
                반갑습니다!!!
                <a href="">@{{user.username}}</a>
            </h2>
        {% endif %}
        <h2>Group</h2>
        <p>여기는 그룹페이지입니다!!!</p>
        
        {% if user.is_authenticated %}
            <a href="{%url 'groups:create'%}" class="btn btn-warning">
                <i class="fab fa-twitter"></i>
                create new Group!!
            </a>
        {% endif %}
        
    </div>
{%endblock%}

{%block group_content%}
<!--그룹 리스트 출력-->
<div class="col-md-8">
    {% for group in group_list %}
    <div class="jumbotron">
        <h3>{{group.name}}</h3>
        <button type="button" class="btn btn-primary">
          Member <span class="badge badge-light">{{group.members.count}}</span>
        </button>
        <a href="{%url 'groups:detail' slug=group.slug%}" class='btn btn-primary'>
            그룹보기
        </a>
    </div>
    {%endfor%}
</div>
{%endblock%}

posts/templates/posts/_post.html
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">{{post.created_at}}</p>
    <p class="card-text">
      <a href="{%url 'posts:userposts' username=post.user.username%}">{{post.user.username}}</a>
    </p>
    <a href="{%url 'posts:detail' username=post.user.username pk=post.pk%}" class="btn btn-primary">자세히</a>
  </div>
</div>

posts/templates/posts/post_base.html
{%extends 'base.html'%}
{%block content%}
    <div class="container">
        <div class="row">
            {%block prepost%} {%endblock%}
            {%block postcontent%} {%endblock%}
            {%block nextpost%} {%endblock%}
        </div>
    </div>
{%endblock%}

posts/templates/posts/post_confirm_delete.html
{%extends 'posts/post_base.html'%}
{%block postcontent%}
    <form method='post'>
        {%csrf_token%}
        <input type="submit" value='삭제?'/>
    </form>
{%endblock%}

posts/templates/posts/post_detail.html
{%extends 'posts/post_base.html'%}
{%block postcontent%}
    <div class="jumbotron">
      <h1 class="display-4">{{post.title}}</h1>
      <p class="lead">{{post.content}}</p>
      <hr class="my-4">
      <p>{{post.user.username}} / {{post.created_at}}</p>
      {%if user.is_authenticated and post.user == user%}
      <a class="btn btn-primary btn-lg" href="{%url 'posts:update' pk=post.pk%}" role="button">수정</a>
      <a class="btn btn-danger btn-lg" href="{%url 'posts:delete' pk=post.pk%}" role="button">삭제</a>
      {%endif%}
    </div>
{%endblock%}

posts/templates/posts/post_form.html
{%extends 'posts/post_base.html'%}
{%load bootstrap4%}

{%block postcontent%}
    <form method='post'>
        {%csrf_token%}
        {%bootstrap_form form%}
        <input type="submit"/>
    </form>
{%endblock%}

posts/templates/posts/post_list.html
{%extends 'posts/post_base.html'%}

{%block prepost%}
    <div class="col-md-4">
        {% if user.is_authenticated %}
            <h2>
                반갑습니다!!!
                <a href="{%url 'posts:userposts' username=user.username%}">@{{user.username}}</a>
            </h2>
        {% endif %}
        <h2>Post</h2>
        <p>여기는 포스트페이지입니다!!!</p>
        
        {% if user.is_authenticated %}
            <a href="{%url 'posts:create'%}" class="btn btn-warning">
                <i class="fab fa-twitter"></i>
                create new Post!!
            </a>
        {% endif %}
    </div>
{%endblock%}

{%block postcontent%}
    <div class="col-md-8">
        <!--게시물 하나씩 출력-->
        {%for post in post_list%}
            {%include 'posts/_post.html'%}
        {%endfor%}
    </div>
{%endblock%}

posts/templates/posts/user_post_list.html
{%extends 'posts/post_base.html'%}

{%block prepost%}
    <div class="col-md-4">
        <h2>{{user.username}}</h2>
    </div>
{%endblock%}

{%block postcontent%}
    <div class="col-md-8">
        <!--게시물 하나씩 출력-->
        {%for post in post_list%}
            {%include 'posts/_post.html'%}
        {%endfor%}
    </div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!--bootstrap CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/social.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{%url 'home'%}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'posts:list'%}">Post<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'groups:list'%}">Group</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link disabled" href="{% url 'accounts:login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a href="{%url 'accounts:signup'%}" class="nav-link disabled">Signup</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {%block content%}
    {%endblock%}
</body>
</html>

templates/bye.html
{%extends 'base.html'%}
{% load staticfiles %}
{%block content%}
    <h1>잘가!!!</h1>
    <img src="{% static 'img/a.jpg'%}"></img>
{%endblock%}

templates/index.html
{%extends 'base.html'%}

{%block content%}
    <h1>인덱스 입니다.</h1>
{%endblock%}